coverage:
  round: down
  precision: 1

# ignore generated files
ignore:
  - "/src/util/ua_eventfilter_grammar.c"
  - "/src/util/ua_eventfilter_lex.c"
  - "/src/util/ua_types_lex.c"
  - "**/src_generated/**"